logging:
  path: ./logs

server:
  port: ${PORT:5003}

spring:
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://192.168.43.191:26257/jalgoarena?sslmode=disable
    username: ${COCKROACH_USERNAME:jalgo}
    password: ${COCKROACH_PASSWORD:}

jalgoarena.security.jwt:
  tokenExpirationTime: 43200 # Minutes
  tokenIssuer: jalgoarena.com
  tokenSigningKey: ${TOKEN_SIGNING_KEY:U9FdVDcRlKRV+WDzSOCmdeKkhR9MWANj1Ksti9GiXPdzgyL4LBGhFLvzDxOkJDg/JvD65s3rbcUda757Re4uAA==}
